http://localhost:3000/perguntas

###

http://localhost:3000/Alunos

###

POST http://localhost:3000/perguntas HTTP/1.1
content-type: application/json

{
      
      "pergunta": "O aluno sabe ler CHINÊS?"
}

###

DELETE http://localhost:3000/Alunos/7 HTTP/1.1
content-type: application/json